import { BuildingDef } from '../types';

export const BUILDINGS: Record<string, BuildingDef> = {
  town_hall: {
    id: 'town_hall',
    name: 'Town Hall',
    category: 'logistics',
    description: 'The administrative heart of your settlement. Houses 6 initial settlers and coordinates builders.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 60 }, { res: 'stone', qty: 30 }],
    buildMs: 25000,
    capacity: 6, // Initial beds
    maxWorkers: 2,
  },
  storehouse: {
    id: 'storehouse',
    name: 'Storehouse',
    category: 'logistics',
    description: 'Expands settlement resource storage capacity by +500 units and acts as a regional delivery hub.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 30 }, { res: 'stone', qty: 15 }],
    buildMs: 15000,
    capacity: 500, // storage boost
  },
  sawmill: {
    id: 'sawmill',
    name: 'Sawmill',
    category: 'production',
    description: 'Employs a Sawyer who fetches 2 Logs from storage and processes them into 1 Wood plank.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 35 }, { res: 'stone', qty: 10 }],
    buildMs: 18000,
    workJob: 'sawyer',
    maxWorkers: 2,
  },
  quarry: {
    id: 'quarry',
    name: 'Stone Quarry',
    category: 'production',
    description: 'Extracts durable stone blocks from nearby rocky outcrop formations.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 25 }],
    buildMs: 14000,
    workJob: 'stone_miner',
    maxWorkers: 2,
  },
  coal_mine: {
    id: 'coal_mine',
    name: 'Coal Mine',
    category: 'industry',
    description: 'Excavates coal seam deposits to fuel smithing furnaces and industrial works.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 30 }, { res: 'stone', qty: 20 }],
    buildMs: 20000,
    workJob: 'coal_miner',
    maxWorkers: 2,
  },
  iron_mine: {
    id: 'iron_mine',
    name: 'Iron Mine',
    category: 'industry',
    description: 'Extracts raw iron ore veins essential for forging weapons, shields, and machinery.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 35 }, { res: 'stone', qty: 25 }],
    buildMs: 22000,
    workJob: 'iron_miner',
    maxWorkers: 2,
  },
  smithy: {
    id: 'smithy',
    name: 'Smithy',
    category: 'industry',
    description: 'Forges tempered steel Swords and iron Shields using Coal and Iron Ore.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 40 }, { res: 'stone', qty: 35 }],
    buildMs: 25000,
    workJob: 'weaponsmith',
    maxWorkers: 2,
  },
  house: {
    id: 'house',
    name: 'Settler House',
    category: 'housing_military',
    description: 'Provides comfortable housing with +4 beds, allowing your settlement population to expand.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 25 }, { res: 'stone', qty: 10 }],
    buildMs: 12000,
    capacity: 4, // 4 beds
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    category: 'housing_military',
    description: 'Equips 1 Villager with 1 Sword and 1 Shield to train them into a combat Soldier.',
    size: { w: 2, h: 2 },
    cost: [{ res: 'wood', qty: 50 }, { res: 'stone', qty: 40 }],
    buildMs: 30000,
    trains: {
      inputUnit: 'villager',
      requires: [
        { res: 'sword', qty: 1 },
        { res: 'shield', qty: 1 },
      ],
      outputUnit: 'soldier',
      timeMs: 10000,
    },
  },
  road: {
    id: 'road',
    name: 'Paved Road',
    category: 'logistics',
    description: 'Cobblestone path that reduces movement cost to 1 (3x faster than wild terrain).',
    size: { w: 1, h: 1 },
    cost: [{ res: 'stone', qty: 1 }],
    buildMs: 1500,
  },
  wall: {
    id: 'wall',
    name: 'Stone Wall',
    category: 'fortifications',
    description: 'Sturdy defensive battlement that blocks ground movement and safeguards your colony.',
    size: { w: 1, h: 1 },
    cost: [{ res: 'stone', qty: 4 }],
    buildMs: 4000,
  },
  gate: {
    id: 'gate',
    name: 'Fortified Gate',
    category: 'fortifications',
    description: 'Passable defensive checkpoint permitting settlers through stone walls.',
    size: { w: 1, h: 1 },
    cost: [{ res: 'wood', qty: 5 }, { res: 'stone', qty: 5 }],
    buildMs: 5000,
  },
  turret: {
    id: 'turret',
    name: 'Defense Turret',
    category: 'fortifications',
    description: 'Automated watchtower with ballista archers that strikes nearby threats (Range 5 tiles).',
    size: { w: 1, h: 1 },
    cost: [{ res: 'wood', qty: 30 }, { res: 'stone', qty: 25 }],
    buildMs: 18000,
    attacks: {
      rangeTiles: 5,
      damage: 15,
      fireMs: 1200,
    },
  },
};

export function getBuilding(id: string): BuildingDef | undefined {
  return BUILDINGS[id];
}

export const BUILDING_IDS = Object.keys(BUILDINGS);
